### ISSUE TITLE
Testing the script not working on MacOS 12.3.1

### ISSUE THREAD

**Issue by stefanhgm** [sdondley/Tab-Through-Google-Results-with-Safari#1]
Hi Steve,

thanks for making your script available!

When I try to test the script as described in the Readme, it only outputs several tabs in my terminal but does not switch to Safari before doing this. Do you know what could cause this issue and if it would still work if I continue with the steps in the Readme?

Cheers

**Comment by sdondley** [comment]
Interesting. I'm seeing the same thing. I think it's probably a permission issue that has changed. Either that or newer versions of MacOS have locked down AppleScript a bit. I'll play with it when I get a chance.

**Comment by sdondley** [comment]
Fixed. Thanks for the report. Not sure how this got changed/broken. Very weird.
